export enum EmailsType {
  VERIFICATION = 'VERIFICATION',
  RESET_PASSWORD = 'RESET_PASSWORD',
  OTHER = 'OTHER',
  WELCOME = 'WELCOME',
  PRODUCT_LISTED = 'PRODUCT_LISTED',
  OBJECTION_RAISED = 'OBJECTION_RAISED',
  OBJECTION_RECEIVED = 'OBJECTION_RECEIVED',
  OBJECTION_REPLY_RECEIVED = 'OBJECTION_REPLY_RECEIVED',
  OBJECTION_REPLY_SENT = 'OBJECTION_REPLY_SENT',
}
