export enum AuctionActions {
  SELLER_DEPOSIT = 'SELLER_DEPOSIT',
  BIDDER_DEPOSIT = 'BIDDER_DEPOSIT',
  SUBMIT_BID = 'SUBMIT_BID',
  BIIDER_PURCHASE = 'BIIDER_PURCHASE',
  BUY_NOW = 'BUY_NOW',
  AUCTION_UPDATE = 'AUCTION_UPDATE',
  AUCTION_DELETE = 'AUCTION_DELETE',
}
